### ISSUE TITLE
No mouse sensitivity, only acceleration

### ISSUE THREAD

**Issue by kostyastrong** [ArtiomSu/kensington-expert-trackball-linux-config#3]
I just want to make my sensitivity a little lower; with current sensitivity the device is hardly called “usable”. This github topic describes how to configurate Kensington Expert without their software. It is true, that you can configure buttons with xinput, but you cannot set sensitivity, again. There is nothing wrong with my trackball or drivers as it seems to be: all buttons are detectable, acceleration works fine, no complains. Only sensitivity is missed, which I’ve been trying to find for a few days. There are sensitivities for the other mices, but not for this one, for some reason. 

I've also tried using [xset](https://wiki.archlinux.org/title/Mouse_acceleration#Using_xset), but with 0 acceleration and 0 threshold mouse is still too fast to use. Forum Manjaro, where[ I opened a discussion ](https://forum.manjaro.org/t/no-sensitivity-for-kensington-expert-wired/113729/3)didn't help either.

Do you know where sensitivity for the Trackball Kensington Expert is? Or, maybe there are the other ways to slow down the trackball.

**Comment by ArtiomSu** [comment]
In the future please read the ReadMe of github projects before creating an "issue"

**Comment by kostyastrong** [comment]
Please answer at least once before closing an "issue". Seriously, I knew that you wanted to remap your buttons, I read the readMe and sh files, trying to solve the sensitivity issue. It's not the problem you had a desire to write an execution file, but I couldn't help resolve my issue, why didn't you try something here?

**Comment by ArtiomSu** [comment]
These is a todo section in the read me which states that it is not possible to change the sensitivity of the ball as its missing that property. 

So please read the readme of projects they are there for a reason.
